#!/run/current-system/sw/bin/bash
set -ex

GUEST_NAME="${1}"
HOOK_NAME="${2}"
STATE_NAME="${3}"
MISC="${@:4}"

HOOKPATH="/etc/libvirt/hooks/qemu.d/${HOOK_NAME}/${STATE_NAME}"

if [ -f "${HOOKPATH}" ] && [ -s "${HOOKPATH}" ] && [ -x "${HOOKPATH}" ]; then
    eval \"$HOOKPATH\" "$@"
fi
