{ ... }:
{
  imports = [
    ./android
    ./appimage
    ./audio
    ./auto-upgrade
    ./boot
    ./display_manager
    ./distrobox
    ./fcitx5
    ./flatpak
    ./font
    ./gnome-disks
    ./gnome-keyring
    ./gnupg
    ./gparted
    ./hd-idle
    ./home-manager
    ./kdiskmark
    ./keyboard
    ./keyd
    ./locale
    ./mango
    ./networking
    ./niri
    ./nix
    ./nixos-generators
    ./nixpkgs
    ./openssh
    ./partition-manager
    ./plasma
    ./plymouth
    ./podman
    ./power-profiles-daemon
    ./printing
    # ./tmux
    ./user
    ./v4l2loopback
    ./virt-manager
    ./ydotool
  ];
}
